profile = "prod"

[server]
addr = "0.0.0.0"
port = 8_080

[db]
host = "127.0.0.1"
port = 5_432
username = "username"
password = "password"
database_name = "database_name"
max_connections = 5

[sentry]
enabled = false
dsn = ""


[secret]
private_access_key = "/var/lib/zm_api/keys/private_access_rsa_key.pem"
public_access_key = "/var/lib/zm_api/keys/public_access_rsa_key.pem"
private_refresh_key = "/var/lib/zm_api/keys/private_refresh_rsa_key.pem"
public_refresh_key = "/var/lib/zm_api/keys/public_refresh_rsa_key.pem"

[http]
timeout = 10
