profile = "prod"

[server]
addr = "0.0.0.0"
port = 8_080

[db]
host = "127.0.0.1"
port = 5_432
username = "username"
password = "password"
database_name = "database_name"
max_connections = 5

[redis]
username = "redis_user"
password = ""
host = "127.0.0.1"
port = 6_379
database_name = ""

[email]
username = "email_user"
password = "email_pass"
host = "smtp.gmail.com"
port = 1_025

[sentry]
key = "https://ceaa8e5d40646d02986f3afecf3807c7@o4507954772705280.ingest.de.sentry.io/4507954781356112"


[secret]
private_access_key = "/var/lib/zm_api/keys/private_access_rsa_key.pem"
public_access_key = "/var/lib/zm_api/keys/public_access_rsa_key.pem"
private_refresh_key = "/var/lib/zm_api/keys/private_refresh_rsa_key.pem"
public_refresh_key = "/var/lib/zm_api/keys/public_refresh_rsa_key.pem"

[worker]
failed_task_delay = 100

[http]
timeout = 10
