profile = "test-db"

[server]
addr = "127.0.0.1"
port = 8080

[db]
host = "127.0.0.1"
port = 3307
username = "zm_test_user"
password = "zm_test_pass"
database_name = "zm_test"
max_connections = 5

[sentry]
enabled = false
dsn = ""

[secret]
private_access_key = "static/key/private_access_rsa_key.pem"
public_access_key = "static/key/public_access_rsa_key.pem"
private_refresh_key = "static/key/private_refresh_rsa_key.pem"
public_refresh_key = "static/key/public_refresh_rsa_key.pem"

[http]
timeout = 10
