profile = "test"

[server]
addr = "127.0.0.1"
port = 8080

[db]
host = "127.0.0.1"
port = 3307
username = "zm_test_user"
password = "zm_test_pass"
database_name = "zm_test"
max_connections = 5

[redis]
username = "redis_user"
password = ""
host = "127.0.0.1"
port = 6_379
database_name = ""

[email]
username = "email_user"
password = "email_pass"
host = "127.0.0.1"
port = 1_025

[sentry]
key = "https://ceaa8e5d40646d02986f3afecf3807c7@o4507954772705280.ingest.de.sentry.io/4507954781356112"

[secret]
private_access_key = "static/key/private_access_rsa_key.pem"
public_access_key = "static/key/public_access_rsa_key.pem"
private_refresh_key = "static/key/private_refresh_rsa_key.pem"
public_refresh_key = "static/key/public_refresh_rsa_key.pem"

[worker]
failed_task_delay = 1

[http]
timeout = 10
